spring.application.name=laos

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/laostravel
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=mySecretKeyForJWTTokenGenerationAndValidationPurposeOnly123456789
jwt.expiration=10800000

# File Upload Configuration
file.upload-dir=uploads/destinations
spring.servlet.multipart.max-file-size=10MB
spring.jackson.serialization.write-dates-as-timestamps=false
spring.servlet.multipart.max-request-size=50MB

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Logging
logging.level.com.traveller.laos=INFO
logging.level.org.springframework.security=WARN
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%level] %logger{36} - %msg%n

# File upload dirs
file.upload-dir-festivals=uploads/festivals
file.upload-dir-articles=uploads/articles
